### ISSUE TITLE
neg_fold_data_{}文件

### ISSUE THREAD

**Issue by liuchenustb** [qiufengyuyi/event_extraction#3]
代码里好像没有neg_fold_data_{}的生成策略？

**Comment by qiufengyuyi** [comment]
> 代码里好像没有neg_fold_data_{}的生成策略？

更新了脚本gen_kfold_data.py，可以再试试看

**Comment by liuchenustb** [comment]
> > 代码里好像没有neg_fold_data_{}的生成策略？
> 
> 更新了脚本gen_kfold_data.py，可以再试试看

应该还是没有生成neg_fold_data_{}文件夹，全文搜索了一下，代码里好像没有np.save("..../neg_fold_data_{}/...".format(),...)的相关代码。

**Comment by liuchenustb** [comment]
已得到解答
